CREATE TABLE categories (id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, nom VARCHAR(80) UNIQUE NOT NULL);
CREATE TABLE livres_categories (livre_id INTEGER REFERENCES livres(id) ON DELETE CASCADE, categorie_id INTEGER REFERENCES categories(id) ON DELETE CASCADE, PRIMARY KEY (livre_id,categorie_id));
